credentials:
  usernames:
    david:
      name: David Nordström
      password: '$2b$12$zV7EQNzC2ZcU2o1FAssX1edRSpJfHZBdjHvwYCtGgfd6.f8d92vwO'  # använd `stauth.Hasher(['123']).generate()` för riktig hashning
      account_type: free

cookie:
  name: some_cookie_name
  key: some_random_key
  expiry_days: 30

preauthorized:
  emails: []