name_to_ticker = {
    # Swedish Large Cap
    "Atlas Copco": "ATCO-B.ST",
    "Investor": "INVE-B.ST",
    "Industrivärden": "INDU-C.ST",
    "Volvo": "VOLV-B.ST",
    "Ericsson": "ERIC-B.ST",
    "H&M": "HM-B.ST",
    "Sandvik": "SAND.ST",
    "Essity": "ESSITY-B.ST",
    "EQT": "EQT.ST",
    "Skanska": "SKA-B.ST",
    "Telia": "TELIA.ST",
    "Nordea": "NDA-SE.ST",
    "Swedbank": "SWED-A.ST",
    "SEB": "SEB-A.ST",
    "Handelsbanken": "SHB-A.ST",
    "SCA": "SCA-B.ST",
    "SSAB": "SSAB-A.ST",
    "Electrolux": "ELUX-B.ST",
    "AstraZeneca": "AZN.ST",
    "Husqvarna": "HUSQ-A.ST",
    "Boliden": "BOL.ST",
    "Tele2": "TEL2-B.ST",
    "SKF": "SKF-B.ST",
    "Assa Abloy": "ASSA-B.ST",
    "Hexagon": "HEXA-B.ST",
    "SEB": "SEB-A.ST",
    "Acreo": "ACRE.ST",  # om Large Cap enligt lista; justera annars

    # Ditt tidigare map
    "Latour": "LATO-B.ST",
    "Kinnevik": "KINV-B.ST",
    "Svolder": "SVOL-B.ST",
    "Spiltan": "SPLT.ST",
    "Lundbergföretagen": "LUND-B.ST",
    "Traction": "TRAC-B.ST",
    "Öresund": "ORES.ST",
    "Flat Capital": "FLAT-B.ST",
    "Creades": "CRED-A.ST",
    "Byggmästare AJA": "BMST-B.ST",
    "Bure": "BURE.ST",

    # Utländska som redan fanns
    "Microsoft": "MSFT",
    "Apple": "AAPL",
    "Alphabet": "GOOGL",
    "Amazon": "AMZN",
}